

# This file was *autogenerated* from the file 2-exp.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_3 = Integer(3)
print("2 to the 3rd power")
print(_sage_const_2 **_sage_const_3 )

