

# This file was *autogenerated* from the file 3-loop.sage
from sage.all_cmdline import *   # import sage library

_sage_const_10 = Integer(10)#example 3: a for loop
for i in range(_sage_const_10 ):
  print(str(i) + ": Hello World")

