

# This file was *autogenerated* from the file 4-permuting.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_26 = Integer(26)#Generate the alphabet
lst = [chr(i) for i in range( ord('A'), (ord('Z') +_sage_const_1 ) ) ]

#Permute the list using a Sage function
lstP = Permutations(lst).random_element()

for i in range(_sage_const_26 ):
 print(lst[i] + ' ' + lstP[i]  + ' ' )

print()
#python also permutes 
import random
import copy
lstPy  = copy.deepcopy(lst) #preserve the original list
random.shuffle(lst) #permute original list
for i in range(_sage_const_26 ):
 print(lstPy[i] + ' ' + lst[i]  + ' ' )


