

# This file was *autogenerated* from the file 5-primes.sage
from sage.all_cmdline import *   # import sage library

_sage_const_10 = Integer(10); _sage_const_31 = Integer(31); _sage_const_1 = Integer(1); _sage_const_11 = Integer(11)#primes 3 ways

#first 10 primes
print(primes_first_n(_sage_const_10 ))
print()

#primes less then 31
print(prime_range(_sage_const_31 ))
print()

#first 10 primes
primes = [nth_prime(x) for x in range(_sage_const_1 ,_sage_const_11 )]
print(primes)




